### ISSUE TITLE
개선사항

### ISSUE THREAD

**Issue by kyjkyj080115** [CwhiteKJ/Miho#2]
배워 커맨드에 replace 를 이용하여 메시지를 보낸 사람이 맨션 되게 된다면 좋겠습니다! 예시를 들어 
**미호야 배워 안녕 {사용자}님 안녕하세요!**    라고 명령어를 쓴 다음  
**미호야 안녕**   이라고 hello 라는 분이 명령어를 치면 미호가 
**@hello 님 안녕하세요!**   라고, waffle 이라는 분이 명령어를 치면
 **@waffle 님 안녕하세요!**  맨션이 될 수 있다면 좋겠습니다!

**Comment by CwhiteKJ** [comment]
added by [here](https://github.com/CwhiteKJ/Miho/commit/c0148c5bef6359748b4f352f91db471e95e297d8#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346)
